### PR TITLE
Update bot.js

### PR DESCRIPTION
**Pull request by numselli**

### CODE REVIEW

**Comment by MutantRabbit767** [comment]
over 3 years late, but thanks 😭
has this been tested? willing to merge into PR for the hell of it.

**Comment by numselli** [comment]
I dont remember if I tested it or not.
Edit; just looked over the code and the changes. The bot uses mongo db so I probably did not test it. Though it does not look like the changes would have an impact

**Comment by MutantRabbit767** [comment]
i can't believe you responded, this makes me so happy NGL.

**Comment by MutantRabbit767** [comment]
apparently because your branch was deleted I cant merge.

**Comment by numselli** [comment]
I made #3 . the first commit is what this pr has right now, the second commit is more changes that I have just made. Once again I have not tested anything.

**Pull request closed without merging**
